---
- name: backup servers
  hosts: all
  strategy: free
  gather_facts: false
  become: true
  tasks:
    - name: set LD message
      ansible.builtin.set_fact:
        lcd_message: "{{ inventory_hostname }} backup started"
    - name: send LCD notification
      ansible.builtin.import_tasks:
        file: notify_lcd.yml
    - name: backup server
      ansible.builtin.command: "/usr/local/bin/backup_cuadro.sh"
      failed_when: false
    - name: Pause for messages to flush
      ansible.builtin.pause:
        seconds: 10
    - name: set LD message
      ansible.builtin.set_fact:
        lcd_message: "{{ inventory_hostname }} backup finished"
    - name: send LCD notification
      ansible.builtin.import_tasks:
        file: notify_lcd.yml
