---
- name: backup servers
  hosts: all
  gather_facts: false
  become: true
  tasks:
    - name: set LD message
      ansible.builtin.set_fact:
        lcd_message: Servers backup started
    - name: send LCD notification
      ansible.builtin.import_tasks:
        file: notify_lcd.yml
    - name: backup server
      ansible.builtin.command: "/usr/local/bin/backup_cuadro.sh"
    - name: Pause for 1 minutes to wait for messages to flush
      ansible.builtin.pause:
        minutes: 1
    - name: set LD message
      ansible.builtin.set_fact:
        lcd_message: Servers backup finished
    - name: send LCD notification
      ansible.builtin.import_tasks:
        file: notify_lcd.yml

