---
- name: disable firewall for 5 minutes
  hosts: all
  gather_facts: false
  become: true
  tasks:
    - name: disable firewall for 5 minutes
      ansible.builtin.command: "/usr/local/bin/pihole disable 5m"
