---
- name: printer on
  hosts: cuadro
  gather_facts: false
  become: true
  tasks:
    - name: printer on
      ansible.builtin.shell: modprobe usblp && gpio write 5 0
    - name: set LD message
      ansible.builtin.set_fact:
        lcd_message: Printer on
    - name: send LCD notification
      ansible.builtin.import_tasks:
        file: notify_lcd.yml

