---
- name: reboot sap servers
  hosts: rpi
  tasks:
    - name: Check that the somefile.conf exists
      stat:
        path: /var/run/reboot-required
      register: kernel_updated
    - name: Reboot the debian box if kernel updated
      reboot:
        msg: "Reboot initiated by Ansible for kernel updates"
        connect_timeout: 5
        reboot_timeout: 300
        pre_reboot_delay: 300
        post_reboot_delay: 30
        test_command: uptime
      when: kernel_updated.stat.exists
