---
- name: shutdown sleepers
  hosts: sleepers
  become: true
  tasks:
    - name: shutdown sleeping servers
      ansible.builtin.command: "/sbin/shutdown -h 1 --no-wall"
      failed_when: false
      when: inventory_hostname in groups['sleepers']
       
