---
- name: shutdown servers
  hosts: all
  gather_facts: false
  become: true
  tasks:
    - name: shutdown server
      ansible.builtin.command: "/sbin/shutdown -h 1 --no-wall"
      failed_when: false
