---
- name: shutdown me
  hosts: localhost
  gather_facts: false
  become: true
  tasks:
    - name: shutdown me
      ansible.builtin.shell: "(sleep 30 ; init 0 --no-wall >/dev/null 2>&1 &)"
      async: 10
      poll: 0
