---
- name: wake up sleeping servers, update and shutdown
  ansible.builtin.import_playbook: wol_sleepers.yml
  ansible.builtin.import_playbook: update_servers.yml
  ansible.builtin.import_playbook: shutdown_sleepers.yml
       
