---
- name: update servers waking up and shutting down some servers
  hosts: all
  gather_facts: false
  become: true
  tasks:
    - name: wake up servers 
      community.general.wakeonlan:
#        mac: "00:1b:78:b6:8a:50"
      mac: "{{ mac }}"
      delegate_to: localhost
      when: inventory_hostname in groups['sleepers']
    - name: wait for sleeping servers to be up
      ansible.builtin.wait_for_connection:
      when: inventory_hostname in groups['sleepers']

    - name: shutdown sleeping servers
      ansible.builtin.command: "/sbin/shutdown -h 0 --no-wall"
      failed_when: false
      when: inventory_hostname in groups['sleepers']
       
